/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202457201056;

/**
 *
 * @author naila
 */
public class Panel_siswa extends javax.swing.JPanel {

    /**
     * Creates new form Panel_siswa
     */
    public Panel_siswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenSiswa = new javax.swing.JPanel();
        PdataSiswa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BiconSilang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTnis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCBjeniskel = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTtempat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTtanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jThp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCkelas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlamat = new javax.swing.JTextArea();
        jBtambah = new javax.swing.JButton();
        jBubah = new javax.swing.JButton();
        jBhapus = new javax.swing.JButton();
        jBreset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        ContenSiswa.setPreferredSize(new java.awt.Dimension(1029, 722));

        PdataSiswa.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("DATA SISWA");

        BiconSilang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-cross-50.png"))); // NOI18N
        BiconSilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiconSilangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PdataSiswaLayout = new javax.swing.GroupLayout(PdataSiswa);
        PdataSiswa.setLayout(PdataSiswaLayout);
        PdataSiswaLayout.setHorizontalGroup(
            PdataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PdataSiswaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BiconSilang)
                .addGap(23, 23, 23))
        );
        PdataSiswaLayout.setVerticalGroup(
            PdataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PdataSiswaLayout.createSequentialGroup()
                .addGroup(PdataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PdataSiswaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BiconSilang))
                    .addGroup(PdataSiswaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FOTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("NIS");

        jLabel4.setText("Nama");

        jTnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnamaActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Kelamin");

        jCBjeniskel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perempuan", "Laki-laki" }));

        jLabel6.setText("Tempat Lahir");

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("HP");

        jThp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThpActionPerformed(evt);
            }
        });

        jLabel9.setText("Kelas");

        jCkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCkelasActionPerformed(evt);
            }
        });

        jLabel10.setText("Alamat");

        jTAlamat.setColumns(20);
        jTAlamat.setRows(5);
        jScrollPane1.setViewportView(jTAlamat);

        jBtambah.setBackground(new java.awt.Color(51, 153, 0));
        jBtambah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBtambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-plus-20.png"))); // NOI18N
        jBtambah.setText("Tambah");

        jBubah.setBackground(new java.awt.Color(255, 153, 0));
        jBubah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-change-20.png"))); // NOI18N
        jBubah.setText("Ubah");
        jBubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBubahActionPerformed(evt);
            }
        });

        jBhapus.setBackground(new java.awt.Color(204, 51, 0));
        jBhapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-delete-20.png"))); // NOI18N
        jBhapus.setText("Hapus");
        jBhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhapusActionPerformed(evt);
            }
        });

        jBreset.setBackground(new java.awt.Color(0, 102, 204));
        jBreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-reset-20 (2).png"))); // NOI18N
        jBreset.setText("Reset");
        jBreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresetActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout ContenSiswaLayout = new javax.swing.GroupLayout(ContenSiswa);
        ContenSiswa.setLayout(ContenSiswaLayout);
        ContenSiswaLayout.setHorizontalGroup(
            ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PdataSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContenSiswaLayout.createSequentialGroup()
                .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenSiswaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenSiswaLayout.createSequentialGroup()
                                .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ContenSiswaLayout.createSequentialGroup()
                                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(157, 157, 157))
                                    .addGroup(ContenSiswaLayout.createSequentialGroup()
                                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTnis, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTnama, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBjeniskel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTtempat))
                                        .addGap(36, 36, 36)))
                                .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jCkelas, 0, 192, Short.MAX_VALUE)
                                    .addComponent(jThp)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jTtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContenSiswaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContenSiswaLayout.createSequentialGroup()
                                .addComponent(jBtambah)
                                .addGap(29, 29, 29)
                                .addComponent(jBubah)
                                .addGap(26, 26, 26)
                                .addComponent(jBhapus)
                                .addGap(30, 30, 30)
                                .addComponent(jBreset)))))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        ContenSiswaLayout.setVerticalGroup(
            ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenSiswaLayout.createSequentialGroup()
                .addComponent(PdataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenSiswaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenSiswaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jThp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenSiswaLayout.createSequentialGroup()
                                .addComponent(jCBjeniskel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTtempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(ContenSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtambah)
                    .addComponent(jBubah)
                    .addComponent(jBhapus)
                    .addComponent(jBreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ContenSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BiconSilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiconSilangActionPerformed
        // TODO add your handling code here:
        ContenSiswa.setVisible(false);
    }//GEN-LAST:event_BiconSilangActionPerformed

    private void jBhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBhapusActionPerformed

    private void jBubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBubahActionPerformed

    private void jThpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jThpActionPerformed

    private void jCkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCkelasActionPerformed

    private void jTnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnamaActionPerformed

    private void jBresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresetActionPerformed
        // TODO add your handling code here:
        jTnis.setText("");
        jTnama.setText("");
        jCBjeniskel.setToolTipText("");
        jTtempat.setText("");
        jTtanggal.setText("");
        jThp.setText("");
        jCkelas.setToolTipText("");
        jTAlamat.setText("");
                
    }//GEN-LAST:event_jBresetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BiconSilang;
    private javax.swing.JPanel ContenSiswa;
    private javax.swing.JPanel PdataSiswa;
    private javax.swing.JButton jBhapus;
    private javax.swing.JButton jBreset;
    private javax.swing.JButton jBtambah;
    private javax.swing.JButton jBubah;
    private javax.swing.JComboBox<String> jCBjeniskel;
    private javax.swing.JComboBox<String> jCkelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAlamat;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jThp;
    private javax.swing.JTextField jTnama;
    private javax.swing.JTextField jTnis;
    private javax.swing.JTextField jTtanggal;
    private javax.swing.JTextField jTtempat;
    // End of variables declaration//GEN-END:variables
}
