/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202457201056;

/**
 *
 * @author naila
 */
public class Panel_abaout extends javax.swing.JPanel {

    /**
     * Creates new form Panel_abaout
     */
    public Panel_abaout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenAbaout = new javax.swing.JPanel();
        Pabout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBicon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        ContenAbaout.setPreferredSize(new java.awt.Dimension(1020, 722));

        Pabout.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("ABOUT US");

        jBicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-cross-50.png"))); // NOI18N
        jBicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaboutLayout = new javax.swing.GroupLayout(Pabout);
        Pabout.setLayout(PaboutLayout);
        PaboutLayout.setHorizontalGroup(
            PaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaboutLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBicon)
                .addGap(58, 58, 58))
        );
        PaboutLayout.setVerticalGroup(
            PaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaboutLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBicon)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaboutLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setText("APLIKASI INI DIBUAT OLEH NAILA BINTI FAUZIAH");

        jLabel3.setText("NIM : 202457201056");

        jLabel4.setText("PROGRAM STUDI S1 SISTEM INFORMASI");

        jLabel5.setText("INSTITUT TEKNOLOGI INFORMASI");

        javax.swing.GroupLayout ContenAbaoutLayout = new javax.swing.GroupLayout(ContenAbaout);
        ContenAbaout.setLayout(ContenAbaoutLayout);
        ContenAbaoutLayout.setHorizontalGroup(
            ContenAbaoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenAbaoutLayout.createSequentialGroup()
                .addGroup(ContenAbaoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pabout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContenAbaoutLayout.createSequentialGroup()
                        .addGroup(ContenAbaoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenAbaoutLayout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jLabel2))
                            .addGroup(ContenAbaoutLayout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(jLabel3))
                            .addGroup(ContenAbaoutLayout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel4))
                            .addGroup(ContenAbaoutLayout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(jLabel5)))
                        .addGap(0, 500, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContenAbaoutLayout.setVerticalGroup(
            ContenAbaoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenAbaoutLayout.createSequentialGroup()
                .addComponent(Pabout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(0, 452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenAbaout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenAbaout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiconActionPerformed
        // TODO add your handling code here:
        ContenAbaout.setVisible(false);
    }//GEN-LAST:event_jBiconActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenAbaout;
    private javax.swing.JPanel Pabout;
    private javax.swing.JButton jBicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
