/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202457201056;

/**
 *
 * @author naila
 */
public class Panel_JUR extends javax.swing.JPanel {

    /**
     * Creates new form Panel_JUR
     */
    public Panel_JUR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenJurusan = new javax.swing.JPanel();
        PdataJur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bcros = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfKodeJur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamaJur = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ttable = new javax.swing.JTable();
        Btambah = new javax.swing.JButton();
        jBubah = new javax.swing.JButton();
        jBhapus = new javax.swing.JButton();
        jBreset = new javax.swing.JButton();

        ContenJurusan.setBackground(new java.awt.Color(204, 204, 204));
        ContenJurusan.setPreferredSize(new java.awt.Dimension(1020, 722));

        PdataJur.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel1.setText("DATA JURUSAN");

        Bcros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-cross-50.png"))); // NOI18N
        Bcros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PdataJurLayout = new javax.swing.GroupLayout(PdataJur);
        PdataJur.setLayout(PdataJurLayout);
        PdataJurLayout.setHorizontalGroup(
            PdataJurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PdataJurLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bcros, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        PdataJurLayout.setVerticalGroup(
            PdataJurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PdataJurLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PdataJurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bcros, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Kode Jurusan");

        tfKodeJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeJurActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nama Jurusan");

        Ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Ttable);

        Btambah.setBackground(new java.awt.Color(0, 153, 51));
        Btambah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Btambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-plus-20.png"))); // NOI18N
        Btambah.setText("Tambah");
        Btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtambahActionPerformed(evt);
            }
        });

        jBubah.setBackground(new java.awt.Color(255, 153, 0));
        jBubah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-change-20.png"))); // NOI18N
        jBubah.setText("Ubah");
        jBubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBubahActionPerformed(evt);
            }
        });

        jBhapus.setBackground(new java.awt.Color(204, 0, 51));
        jBhapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-delete-20.png"))); // NOI18N
        jBhapus.setText("Hapus");
        jBhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhapusActionPerformed(evt);
            }
        });

        jBreset.setBackground(new java.awt.Color(0, 51, 255));
        jBreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201056/icons8-reset-20 (2).png"))); // NOI18N
        jBreset.setText("Reset");
        jBreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenJurusanLayout = new javax.swing.GroupLayout(ContenJurusan);
        ContenJurusan.setLayout(ContenJurusanLayout);
        ContenJurusanLayout.setHorizontalGroup(
            ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenJurusanLayout.createSequentialGroup()
                .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenJurusanLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKodeJur, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(72, 72, 72)
                        .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfNamaJur, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContenJurusanLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jBubah)
                        .addGap(28, 28, 28)
                        .addComponent(jBhapus)
                        .addGap(26, 26, 26)
                        .addComponent(jBreset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenJurusanLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(474, Short.MAX_VALUE))
            .addComponent(PdataJur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ContenJurusanLayout.setVerticalGroup(
            ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenJurusanLayout.createSequentialGroup()
                .addComponent(PdataJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNamaJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKodeJur, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ContenJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfKodeJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeJurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodeJurActionPerformed

    private void BtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtambahActionPerformed

    private void jBubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBubahActionPerformed

    private void jBhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBhapusActionPerformed

    private void jBresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresetActionPerformed
        // TODO add your handling code here:
       tfKodeJur.setText("");
       tfNamaJur.setText("");
       
        
    }//GEN-LAST:event_jBresetActionPerformed

    private void BcrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcrosActionPerformed
        // TODO add your handling code here:
        ContenJurusan.setVisible(false);
    }//GEN-LAST:event_BcrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcros;
    private javax.swing.JButton Btambah;
    private javax.swing.JPanel ContenJurusan;
    private javax.swing.JPanel PdataJur;
    private javax.swing.JTable Ttable;
    private javax.swing.JButton jBhapus;
    private javax.swing.JButton jBreset;
    private javax.swing.JButton jBubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfKodeJur;
    private javax.swing.JTextField tfNamaJur;
    // End of variables declaration//GEN-END:variables
}
